name: CI - Build Site
on:
  push:
    branches-ignore:
      - gh-pages
  workflow_dispatch:
  pull_request:

permissions:
  contents: write

jobs:
  build:
    name: Build Site and Deploy
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Nekrosis-ISS-Capstone'
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install
        run: npm install

      - name: Build
        run: npm run docs:build

      - name: List contents of dist
        run: ls -R docs/.vitepress/dist/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/.vitepress/dist/
          CLEAN: true
